const books = [
  {
    name: "Animal Farm",
    imgUrl: "../img/Animal_Farm-transformed.jpeg",
    author: "George Orwell",
    desc: "Animal Farm by George Orwell is an allegorical work of  fiction. Depicting rising revolt among the animals, who wish to take  over the humans, the author wrote one of the best satire of the era.  Animals, who live in Mr. Jones farm are tired of serving human and find  it very exploiting as they use animals for all their needs. Rebellion  starts on the day when Mr. Jones forgets to feed the animals. Under the  charge of two pigs: Napoleon and Snowball, animals thus plan to invade  humans and take over the farm.",
    smallDesc:
      "Animal Farm depicts a farm's uprising, echoing the pitfalls of power as animals strive for equality, only to succumb to corruption and tyranny. Orwell's novella serves as a stark warning, illustrating the dangers of totalitarianism and the betrayal of ideals.",
    price: "200",
    ratings: "4.9",
    language: "English",
    paperback: "120",
    itemweight: "100",
    genericname: "Book",
    noOfReviews: "2",
  },
  {
    name: "The Castle",
    imgUrl: "../img/TheCastel.jpeg",
    author: "Franz Kafka",
    desc: "The Castle is a novel by Franz Kafka. It tells the story of a man named K., who is mistaken for a land surveyor and arrives at a village with the intention of working there. However, upon his arrival, he finds himself unable to communicate with the villagers and struggles to gain access to the castle, which holds a mysterious power over the village.",
    smallDesc:
      "The Castle is a haunting exploration of bureaucracy, power, and the individual's struggle against oppressive systems. Kafka's surreal narrative delves into themes of alienation and existential angst, leaving readers questioning the nature of authority and identity.",
    price: "250",
    ratings: "4.5",
    language: "English",
    paperback: "352",
    itemweight: "200",
    genericname: "Book",
  },
  {
    name: "Ikigai",
    imgUrl: "../img/ikigai.jpg",
    author: "Héctor García and Francesc Miralles",
    desc: "Ikigai: The Japanese Secret to a Long and Happy Life explores the concept of ikigai, which translates to 'reason for being' in English. Drawing on Japanese philosophy and culture, the book examines how finding one's ikigai can lead to a fulfilling and purposeful life. Through interviews with centenarians and insights from neuroscience, the authors offer practical advice on discovering and pursuing one's passions.",
    smallDesc:
      "Ikigai offers a refreshing perspective on living a meaningful life, blending ancient wisdom with modern science. García and Miralles guide readers on a journey to uncover their purpose, encouraging self-reflection and personal growth along the way.",
    price: "150",
    ratings: "4.8",
    language: "English",
    paperback: "208",
    itemweight: "250",
    genericname: "Book",
  },
  {
    name: "Sapiens",
    imgUrl: "../img/sapiens.jpeg",
    author: "Yuval Noah Harari",
    desc: "Sapiens: A Brief History of Humankind by Yuval Noah Harari offers a sweeping overview of human history, from the emergence of Homo sapiens in Africa to the present day. Drawing on insights from biology, anthropology, and history, Harari explores key developments such as the Agricultural Revolution, the rise of empires, and the scientific revolution. He also examines the impact of these developments on human societies and the planet as a whole.",
    smallDesc:
      "Sapiens is a thought-provoking exploration of the human experience, challenging readers to rethink their understanding of history and civilization. Harari's accessible writing style and interdisciplinary approach make complex concepts accessible to a wide audience.",
    price: "180",
    ratings: "4.7",
    language: "English",
    paperback: "464",
    itemweight: "300",
    genericname: "Book",
  },
  {
    name: "Metamorphosis",
    imgUrl: "../img/metamorphosis.jpg",
    author: "Franz Kafka",
    desc: "Metamorphosis is a novella by Franz Kafka. It tells the story of Gregor Samsa, a young man who wakes up one morning to find himself transformed into a giant insect. As Gregor struggles to come to terms with his new identity, he faces rejection from his family and society. The novella explores themes of alienation, identity, and the absurdity of existence.",
    smallDesc:
      "Metamorphosis is a surreal and unsettling exploration of the human condition, blending elements of horror, comedy, and existentialism. Kafka's nightmarish narrative challenges readers to confront the limits of empathy and the nature of self.",
    price: "170",
    ratings: "4.6",
    language: "English",
    paperback: "224",
    itemweight: "180",
    genericname: "Book",
  },
  {
    name: "Company of One",
    imgUrl: "../img/companyOfOne.jpg",
    author: "Paul Jarvis",
    desc: "Company of One: Why Staying Small Is the Next Big Thing for Business by Paul Jarvis challenges the traditional growth mindset of entrepreneurship. Drawing on his own experiences as a freelancer and consultant, Jarvis argues that staying small can lead to greater freedom, flexibility, and sustainability. He offers practical advice on building a business that prioritizes quality over quantity, emphasizing the importance of staying true to one's values and vision.",
    smallDesc:
      "Company of One offers a refreshing perspective on entrepreneurship, debunking the myth that bigger is always better. Jarvis's insightful commentary and actionable strategies make this book a valuable resource for anyone looking to build a sustainable business on their own terms.",
    price: "220",
    ratings: "4.8",
    language: "English",
    paperback: "272",
    itemweight: "230",
    genericname: "Book",
  },
  {
    name: "Jane Eyre",
    imgUrl: "../img/JaneEyre.jpg",
    author: "Charlotte Brontë",
    desc: "Jane Eyre is a novel by Charlotte Brontë. It follows the story of Jane Eyre, an orphan who becomes a governess and falls in love with her employer, Mr. Rochester. However, their relationship is complicated by Mr. Rochester's dark secrets and the presence of his mad wife, Bertha. As Jane navigates the challenges of love, morality, and independence, she emerges as a strong and resilient heroine.",
    smallDesc:
      "Jane Eyre is a timeless classic that continues to captivate readers with its richly drawn characters and gripping narrative. Brontë's exploration of social class, gender roles, and the search for identity remains as relevant today as it was in the 19th century.",
    price: "190",
    ratings: "4.7",
    language: "English",
    paperback: "624",
    itemweight: "350",
    genericname: "Book",
  },
  {
    name: "Nineteen Eighty-Four",
    imgUrl: "../img/NineteenEightyFour.jpg",
    author: "George Orwell",
    desc: "Nineteen Eighty-Four is a dystopian novel by George Orwell. It is set in a totalitarian regime ruled by the Party and its leader, Big Brother. The story follows Winston Smith, a low-ranking member of the Party, who rebels against the oppressive government and seeks freedom of thought and expression. As Winston navigates the dangers of surveillance and propaganda, he grapples with questions of truth, reality, and the nature of power.",
    smallDesc:
      "Nineteen Eighty-Four is a chilling portrayal of a dystopian society, where freedom is restricted and truth is manipulated for political gain. Orwell's prophetic vision of surveillance and censorship remains eerily relevant in today's world, making this novel a must-read for anyone concerned about the erosion of civil liberties.",
    price: "210",
    ratings: "4.9",
    language: "English",
    paperback: "328",
    itemweight: "270",
    genericname: "Book",
  },
];

export default books;
